--CREATE DATABASE squadra;

CREATE TABLE TB_PESSOA 
(
  CODIGO_PESSOA BIGINT NOT NULL 
, NOME VARCHAR(256) NOT NULL 
, SOBRENOME VARCHAR(256) NOT NULL 
, IDADE SMALLINT NOT NULL 
, LOGIN VARCHAR(50) NOT NULL 
, SENHA VARCHAR(50) NOT NULL 
, STATUS SMALLINT NOT NULL 
, CONSTRAINT TB_PESSOA_PK PRIMARY KEY 
  (
    CODIGO_PESSOA 
  )
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE TB_UF 
(
  CODIGO_UF BIGINT NOT NULL 
, SIGLA VARCHAR(3) NOT NULL 
, NOME VARCHAR(60) NOT NULL 
, STATUS SMALLINT NOT NULL 
, CONSTRAINT TB_UF_PK PRIMARY KEY 
  (
    CODIGO_UF 
  )
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE TB_MUNICIPIO 
(
  CODIGO_MUNICIPIO BIGINT NOT NULL 
, CODIGO_UF BIGINT NOT NULL 
, NOME VARCHAR(256) 
, STATUS SMALLINT 
, CONSTRAINT TB_MUNICIPIO_PK PRIMARY KEY 
  (
    CODIGO_MUNICIPIO 
  )
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE TB_BAIRRO 
(
  CODIGO_BAIRRO BIGINT NOT NULL 
, CODIGO_MUNICIPIO BIGINT NOT NULL 
, NOME VARCHAR(256) NOT NULL 
, STATUS SMALLINT 
, CONSTRAINT TB_BAIRRO_PK PRIMARY KEY 
  (
    CODIGO_BAIRRO 
  )
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE TB_ENDERECO 
(
  CODIGO_ENDERECO BIGINT NOT NULL 
, CODIGO_PESSOA BIGINT NOT NULL 
, CODIGO_BAIRRO BIGINT NOT NULL 
, NOME_RUA VARCHAR(256) NOT NULL 
, NUMERO VARCHAR(10) NOT NULL 
, COMPLEMENTO VARCHAR(20) 
, CEP VARCHAR(10) NOT NULL 
, CONSTRAINT TB_ENDERECO_PK PRIMARY KEY 
  (
    CODIGO_ENDERECO 
  )
);

ALTER TABLE TB_BAIRRO
ADD CONSTRAINT TB_BAIRRO_FK1 FOREIGN KEY
(
  CODIGO_MUNICIPIO 
)
REFERENCES TB_MUNICIPIO
(
  CODIGO_MUNICIPIO 
)
;

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT TB_ENDERECO_FK1 FOREIGN KEY
(
  CODIGO_PESSOA 
)
REFERENCES TB_PESSOA
(
  CODIGO_PESSOA 
)
;

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT TB_ENDERECO_FK2 FOREIGN KEY
(
  CODIGO_BAIRRO 
)
REFERENCES TB_BAIRRO
(
  CODIGO_BAIRRO 
)
;

ALTER TABLE TB_MUNICIPIO
ADD CONSTRAINT TB_MUNICIPIO_FK1 FOREIGN KEY
(
  CODIGO_UF 
)
REFERENCES TB_UF
(
  CODIGO_UF 
)
;

COMMENT ON COLUMN TB_UF.STATUS IS '1 - ATIVADO
2 - DESATIVADO';

COMMENT ON COLUMN TB_MUNICIPIO.STATUS IS '1 - ATIVADO
2 - DESATIVADO';

COMMENT ON COLUMN TB_BAIRRO.STATUS IS '1- ATIVADO
2- DESATIVADO';

COMMENT ON COLUMN TB_PESSOA.STATUS IS '1 - ATIVADO
2 - DESATIVADO';


CREATE SEQUENCE SEQUENCE_PESSOA INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 /* Warning: NOCACHE */;
CREATE SEQUENCE SEQUENCE_ENDERECO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 /* Warning: NOCACHE */;
CREATE SEQUENCE SEQUENCE_BAIRRO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 /* Warning: NOCACHE */;
CREATE SEQUENCE SEQUENCE_MUNICIPIO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 /* Warning: NOCACHE */;
CREATE SEQUENCE SEQUENCE_UF INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 /* Warning: NOCACHE */;
